"""Austrian-specific detection patterns for Anomyze."""

from anomyze.patterns.at_patterns import (
    COMPANY_CONTEXT_PATTERNS,
    NORMAL_CONTEXT_WORDS,
    ENTITY_BLACKLIST,
    find_emails_regex,
    find_titled_names_regex,
    find_labeled_names_regex,
    find_ibans_regex,
    find_svnr_regex,
    find_tax_number_regex,
    find_birth_date_regex,
    find_aktenzahl_regex,
    find_passport_regex,
    find_id_card_regex,
    find_license_plate_regex,
    find_phone_regex,
    find_address_regex,
    is_blacklisted,
)

__all__ = [
    "COMPANY_CONTEXT_PATTERNS",
    "NORMAL_CONTEXT_WORDS",
    "ENTITY_BLACKLIST",
    "find_emails_regex",
    "find_titled_names_regex",
    "find_labeled_names_regex",
    "find_ibans_regex",
    "find_svnr_regex",
    "find_tax_number_regex",
    "find_birth_date_regex",
    "find_aktenzahl_regex",
    "find_passport_regex",
    "find_id_card_regex",
    "find_license_plate_regex",
    "find_phone_regex",
    "find_address_regex",
    "is_blacklisted",
]
